# Generated by Django 6.0.3 on 2026-03-19 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_root', models.CharField(blank=True, max_length=512)),
                ('default_quota_gb', models.IntegerField(default=0)),
                ('max_upload_gb', models.IntegerField(default=10)),
                ('trash_retention_days', models.IntegerField(default=1)),
                ('auto_purge', models.BooleanField(default=False)),
                ('share_expire_days', models.IntegerField(default=0)),
                ('allow_register', models.BooleanField(default=False)),
                ('enable_logging', models.BooleanField(default=True)),
                ('log_retention_days', models.IntegerField(default=90)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('rename', 'Rename'), ('move', 'Move'), ('share', 'Share'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=512)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
