# Generated by Django 6.0.3 on 2026-03-22 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_systemsettings_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_path', models.CharField(blank=True, help_text='Path ปลายทาง เช่น D:\\Backup หรือ /mnt/backup', max_length=1024)),
                ('enabled', models.BooleanField(default=False)),
                ('schedule', models.CharField(choices=[('manual', 'Manual เท่านั้น'), ('daily', 'ทุกวัน'), ('weekly', 'ทุกสัปดาห์')], default='manual', max_length=20)),
                ('schedule_hour', models.IntegerField(default=2, help_text='ชั่วโมงที่ทำ backup (0-23)')),
                ('schedule_weekday', models.IntegerField(default=0, help_text='วันที่ทำ backup (0=จันทร์ ... 6=อาทิตย์) สำหรับ weekly')),
                ('keep_versions', models.IntegerField(default=3, help_text='จำนวนรุ่นที่เก็บไว้')),
                ('include_trashed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Config',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'กำลังทำงาน'), ('success', 'สำเร็จ'), ('failed', 'ล้มเหลว')], default='running', max_length=20)),
                ('triggered_by', models.CharField(default='manual', max_length=50)),
                ('destination', models.CharField(blank=True, max_length=1024)),
                ('files_copied', models.IntegerField(default=0)),
                ('bytes_copied', models.BigIntegerField(default=0)),
                ('version_name', models.CharField(blank=True, max_length=100)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
