# Generated by Django 6.0.3 on 2026-03-23 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_backupconfig_backuplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_quota_gb', models.IntegerField(blank=True, help_text='quota เฉพาะบุคคล (GB) — None = ใช้ค่า default จาก SystemSettings', null=True)),
                ('destination_path', models.CharField(blank=True, help_text='Path ปลายทาง เช่น D:\\Backup หรือ /mnt/backup', max_length=1024)),
                ('enabled', models.BooleanField(default=False)),
                ('schedule', models.CharField(choices=[('manual', 'Manual เท่านั้น'), ('daily', 'ทุกวัน'), ('weekly', 'ทุกสัปดาห์')], default='manual', max_length=20)),
                ('schedule_hour', models.IntegerField(default=2, help_text='ชั่วโมงที่ทำ backup (0-23)')),
                ('schedule_weekday', models.IntegerField(default=0, help_text='วันที่ทำ backup (0=จันทร์ ... 6=อาทิตย์) สำหรับ weekly')),
                ('keep_versions', models.IntegerField(default=3, help_text='จำนวนรุ่นที่เก็บไว้')),
                ('include_trashed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Config',
            },
        ),
        migrations.DeleteModel(
            name='BackupConfig',
        ),
    ]
