# Generated by Django 6.0.3 on 2026-03-23 01:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_delete_backupconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_path', models.CharField(blank=True, help_text='Path ปลายทาง เช่น D:\\Backup หรือ /mnt/backup', max_length=1024)),
                ('enabled', models.BooleanField(default=False)),
                ('schedule', models.CharField(choices=[('manual', 'Manual เท่านั้น'), ('daily', 'ทุกวัน'), ('weekly', 'ทุกสัปดาห์')], default='manual', max_length=20)),
                ('schedule_hour', models.IntegerField(default=2, help_text='ชั่วโมงที่ทำ backup (0-23)')),
                ('schedule_weekday', models.IntegerField(default=0, help_text='วันที่ทำ backup (0=จันทร์ ... 6=อาทิตย์) สำหรับ weekly')),
                ('keep_versions', models.IntegerField(default=3, help_text='จำนวนรุ่นที่เก็บไว้')),
                ('include_trashed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Config',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='destination_path',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='include_trashed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='keep_versions',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='schedule_hour',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='schedule_weekday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
