print("Count down")
print(10,9,8,7,6,5,4,3,2,1, sep = ' : ' , end = " Zero ")
print(0)
print("Count")
print(1,2,3,4,5,6,7,8,9, sep = ' > ' , end = " Stop \n")
print("End Count")
print()
print("My First", end = ' ')
print("Program")
print("By")
print("Python.")